# Generated by Django 4.2.16 on 2024-10-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('Id_E', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Ev', models.CharField(max_length=30)),
                ('Descripcion', models.TextField()),
                ('Tematica', models.CharField(max_length=60)),
                ('Duracion', models.FloatField()),
                ('Estado', models.BooleanField()),
                ('Ubicacion', models.CharField(max_length=50)),
                ('Fecha_In', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('ID_Sp', models.AutoField(primary_key=True, serialize=False)),
                ('Logotipo', models.URLField(blank=True, max_length=255)),
                ('Nombre', models.CharField(max_length=35)),
                ('Estado', models.BooleanField()),
                ('Contacto', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventoSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evento_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEventos.evento')),
                ('Sponsor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEventos.sponsor')),
            ],
            options={
                'unique_together': {('Evento_Id', 'Sponsor_Id')},
            },
        ),
        migrations.CreateModel(
            name='AdminEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.administrador')),
                ('Evento_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEventos.evento')),
            ],
            options={
                'unique_together': {('Admin_ID', 'Evento_ID')},
            },
        ),
    ]
