# Generated by Django 4.2.16 on 2024-11-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='Duracion',
            new_name='duracion',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='Estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='Fecha_In',
            new_name='fecha_f',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='Ubicacion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='Tematica',
            new_name='tematica',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='Logotipo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='Id_E',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='Nombre_Ev',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='ID_Sp',
        ),
        migrations.AddField(
            model_name='evento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
