# Generated by Django 4.2.16 on 2024-11-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0002_rename_descripcion_evento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_i',
            field=models.DateField(auto_now_add=True, default='2024-11-08'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_f',
            field=models.DateField(auto_now_add=True),
        ),
    ]
