# Generated by Django 4.2.16 on 2024-11-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0003_evento_fecha_i_alter_evento_fecha_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
