# Generated by Django 4.2.16 on 2024-11-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0004_alter_evento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha_f',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_i',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_fn',
            field=models.DateField(default='2024-11-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_in',
            field=models.DateField(default='2024-11-08'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
