# Generated by Django 4.2.16 on 2024-11-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0005_remove_evento_fecha_f_remove_evento_fecha_i_and_more'),
    ]

