# Generated by Django 4.2.16 on 2024-11-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0006_alter_evento_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='id',
            new_name='ID_E',
        ),
    ]
