# Generated by Django 4.2.16 on 2024-11-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0007_rename_id_evento_id_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fn',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_in',
            field=models.DateField(auto_now_add=True),
        ),
    ]
