# Generated by Django 4.2.16 on 2024-11-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0008_alter_evento_fecha_fn_alter_evento_fecha_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='ID_E',
            new_name='id',
        ),
    ]
