# Generated by Django 4.2.16 on 2024-11-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0009_rename_id_e_evento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='duracion',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='direccion_web',
            field=models.URLField(default='http://localhost:3000'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
