# Generated by Django 4.2.16 on 2024-11-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0010_remove_evento_duracion_sponsor_direccion_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
