# Generated by Django 4.2.16 on 2024-10-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVotos', '0002_alter_voto_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='estrellas',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
