# Generated by Django 4.2.16 on 2024-10-23 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionEscultores', '0009_alter_escultor_dni_esc_alter_escultor_telefono_and_more'),
        ('gestionVotos', '0003_voto_estrellas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='visitante',
            new_name='votante',
        ),
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together={('votante', 'escultura')},
        ),
    ]
