# Generated by Django 4.2.16 on 2024-10-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEscultores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='DNI_Adm',
        ),
        migrations.RemoveField(
            model_name='escultor',
            name='DNI_Adm',
        ),
        migrations.RemoveField(
            model_name='escultura',
            name='DNI_Esc',
        ),
        migrations.AlterUniqueTogether(
            name='eventosponsor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventosponsor',
            name='Evento_Id',
        ),
        migrations.RemoveField(
            model_name='eventosponsor',
            name='Sponsor_Id',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='Escultura_ID',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='Evento_ID',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='DNI_Vis',
        ),
        migrations.DeleteModel(
            name='AdminEvento',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Escultor',
        ),
        migrations.DeleteModel(
            name='Escultura',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='EventoSponsor',
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='Visitante',
        ),
    ]
