# Generated by Django 4.2.16 on 2024-10-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEscultores', '0007_escultor_id_esc_escultor_apellido_escultor_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escultura',
            old_name='DNI_Esc',
            new_name='id',
        ),
    ]
