# Generated by Django 4.2.16 on 2024-10-23 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEscultores', '0008_rename_dni_esc_escultura_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escultor',
            name='DNI_Esc',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='escultor',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='escultura',
            name='Tematica',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='escultura',
            name='Titulo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='File_Path',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='File_Type',
            field=models.CharField(max_length=30),
        ),
    ]
