# Generated by Django 4.2.16 on 2024-10-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEscultores', '0010_remove_escultor_id_esc'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediafile',
            name='media_file_constraint',
        ),
        migrations.RenameField(
            model_name='escultor',
            old_name='Biografia',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='escultor',
            old_name='DNI_Esc',
            new_name='dni_esc',
        ),
        migrations.RenameField(
            model_name='escultor',
            old_name='Fecha_Nac',
            new_name='fecha_nac',
        ),
        migrations.RenameField(
            model_name='escultor',
            old_name='Nacionalidad',
            new_name='nacionalidad',
        ),
        migrations.RenameField(
            model_name='escultura',
            old_name='id',
            new_name='escultor',
        ),
        migrations.RenameField(
            model_name='escultura',
            old_name='Fecha_creacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='escultura',
            old_name='ID_Escultura',
            new_name='id_escultura',
        ),
        migrations.RenameField(
            model_name='escultura',
            old_name='Intencion',
            new_name='intencion',
        ),
        migrations.RenameField(
            model_name='escultura',
            old_name='Tematica',
            new_name='tematica',
        ),
        migrations.RenameField(
            model_name='escultura',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='Escultura_ID',
            new_name='escultura_id',
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='Evento_ID',
            new_name='evento_id',
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='File_Path',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='File_Type',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='ID_Media',
            new_name='id_media',
        ),
        migrations.RemoveField(
            model_name='escultura',
            name='Cant_votos',
        ),
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('escultura_id__isnull', False), ('evento_id__isnull', True)), models.Q(('escultura_id__isnull', True), ('evento_id__isnull', False)), _connector='OR'), name='media_file_constraint'),
        ),
        migrations.AddField(
            model_name='escultura',
            name='cant_votos',
            field=models.IntegerField(default=0),
        ),
    ]
