# Generated by Django 4.2.16 on 2024-11-04 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0002_rename_descripcion_evento_descripcion_and_more'),
        ('gestionEscultores', '0010_remove_escultor_id_esc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escultor',
            old_name='Biografia',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='escultor',
            old_name='DNI_Esc',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='escultor',
            old_name='Fecha_Nac',
            new_name='fecha_nac',
        ),
        migrations.RenameField(
            model_name='escultor',
            old_name='Nacionalidad',
            new_name='nacionalidad',
        ),
        migrations.RenameField(
            model_name='escultura',
            old_name='Fecha_creacion',
            new_name='fecha_presentacion',
        ),
        migrations.RenameField(
            model_name='escultura',
            old_name='Tematica',
            new_name='tematica',
        ),
        migrations.RenameField(
            model_name='escultura',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='escultura',
            name='ID_Escultura',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='Evento_ID',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='ID_Media',
        ),
        migrations.AddField(
            model_name='escultura',
            name='id_escultor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEscultores.escultor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escultura',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEventos.evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediafile',
            name='id',
            field=models.BigAutoField(auto_created=True,primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escultura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
