# Generated by Django 4.2.16 on 2024-11-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEscultores', '0011_rename_biografia_escultor_biografia_and_more'),
    ]
