# Generated by Django 4.2.16 on 2024-11-05 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEscultores', '0012_remove_mediafile_media_file_constraint'),
    ]

    # # operations = [
    # #     migrations.RemoveConstraint(
    # #         model_name='mediafile',
    # #         name='media_file_constraint',
    # #     ),
    # # ]
