# Generated by Django 4.2.16 on 2024-11-12 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0010_remove_evento_duracion_sponsor_direccion_web_and_more'),
        ('gestionEscultores', '0013_remove_mediafile_media_file_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscultorInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.CheckConstraint(check=models.Q(('Escultura_ID__isnull', False), ('Escultura_ID__isnull', True), _connector='OR'), name='media_file_constraint'),
        ),
        migrations.AddField(
            model_name='escultorinvitado',
            name='id_escultor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionEscultores.escultor'),
        ),
        migrations.AddField(
            model_name='escultorinvitado',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEventos.evento'),
        ),
    ]
