# Generated by Django 4.2.16 on 2024-11-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEscultores', '0014_escultorinvitado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
