# Generated by Django 4.2.16 on 2024-10-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestionUsuarios', '0002_alter_persona_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Foto_Perfil',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Telefono',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='Apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='DNI',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='Nombre',
        ),
        migrations.AddField(
            model_name='persona',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece el usuario.', related_name='persona_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='persona',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(default='0000', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='persona_user_permissions_set', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default='perez', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.CharField(default=1000, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='pancho', max_length=100),
            preserve_default=False,
        ),
    ]
