# Generated by Django 4.2.16 on 2024-10-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0003_rename_email_persona_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nick',
            field=models.CharField(default='nahu123', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
