# Generated by Django 4.2.16 on 2024-10-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0004_persona_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
