# Generated by Django 4.2.16 on 2024-11-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0006_remove_visitante_dni_vis_administrador_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='apellido',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='nombre',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='Fecha_cr',
            field=models.DateField(auto_now_add=True),
        ),
    ]
