# Generated by Django 4.2.16 on 2024-10-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escultor',
            fields=[
                ('DNI_Esc', models.AutoField(primary_key=True, serialize=False)),
                ('Nacionalidad', models.CharField(max_length=40)),
                ('Fecha_Nac', models.DateField()),
                ('Biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Escultura',
            fields=[
                ('ID_Escultura', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_creacion', models.DateField()),
                ('Titulo', models.CharField(max_length=55)),
                ('Intencion', models.TextField()),
                ('Cant_votos', models.IntegerField()),
                ('DNI_Esc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEscultores.escultor')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('Id_E', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Ev', models.CharField(max_length=30)),
                ('Descripcion', models.TextField()),
                ('Tematica', models.CharField(max_length=60)),
                ('Duracion', models.FloatField()),
                ('Estado', models.BooleanField()),
                ('Ubicacion', models.CharField(max_length=50)),
                ('Fecha_In', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('DNI', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Nombre', models.CharField(max_length=35)),
                ('Apellido', models.CharField(max_length=35)),
                ('Telefono', models.BigIntegerField()),
                ('Foto_Perfil', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('ID_Sp', models.AutoField(primary_key=True, serialize=False)),
                ('Logotipo', models.URLField(blank=True, max_length=255)),
                ('Nombre', models.CharField(max_length=35)),
                ('Estado', models.BooleanField()),
                ('Contacto', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('DNI_Adm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestionEscultores.persona')),
                ('Fecha_cr', models.DateField()),
                ('Rol', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('DNI_Vis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestionEscultores.persona')),
                ('Localidad', models.CharField(max_length=50)),
                ('Codigo_Postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('ID_Media', models.AutoField(primary_key=True, serialize=False)),
                ('File_Path', models.CharField(max_length=255)),
                ('File_Type', models.CharField(max_length=50)),
                ('Escultura_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionEscultores.escultura')),
                ('Evento_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionEscultores.evento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evento_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEscultores.evento')),
                ('Sponsor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEscultores.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='AdminEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evento_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEscultores.evento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('Escultura_ID__isnull', False), ('Evento_ID__isnull', True)), models.Q(('Escultura_ID__isnull', True), ('Evento_ID__isnull', False)), _connector='OR'), name='media_file_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='eventosponsor',
            unique_together={('Evento_Id', 'Sponsor_Id')},
        ),
        migrations.AddField(
            model_name='escultor',
            name='DNI_Adm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionEscultores.administrador'),
        ),
        migrations.AddField(
            model_name='adminevento',
            name='Admin_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEscultores.administrador'),
        ),
        migrations.AlterUniqueTogether(
            name='adminevento',
            unique_together={('Admin_ID', 'Evento_ID')},
        ),
    ]
