# Generated by Django 4.2.16 on 2024-10-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEventos', '0001_initial'),
        ('gestionEscultores', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('ID_Media', models.AutoField(primary_key=True, serialize=False)),
                ('File_Path', models.CharField(max_length=255)),
                ('File_Type', models.CharField(max_length=50)),
                ('Escultura_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionEscultores.escultura')),
                ('Evento_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionEventos.evento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('Escultura_ID__isnull', False), ('Evento_ID__isnull', True)), models.Q(('Escultura_ID__isnull', True), ('Evento_ID__isnull', False)), _connector='OR'), name='media_file_constraint'),
        ),
    ]
