# Generated by Django 4.2.16 on 2024-10-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEscultores', '0004_mediafile_mediafile_media_file_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='escultura',
            name='Tematica',
            field=models.CharField(default='Sin temática', max_length=100),
            preserve_default=False,
        ),
    ]
